version: '2'
services:
  library:
    build:
      context: . 
      args:
       - http_proxy=http://xxx/
       - https_proxy=http://xxx/
    ports:
     - "8080:8080"
    links:
     - db
  db:
   image: alpine-mongodb 
